name: admin_picco
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2

  percent_indicator: ^4.0.1
  provider: ^6.0.2
  lottie: ^1.3.0
  readmore: ^2.1.0
  cached_network_image: ^3.2.1
  logger: 1.1.0

  # For backend data
  firebase_auth: ^3.3.19
  firebase_core: ^1.17.1
  cloud_firestore: ^3.1.17
  firebase_storage: ^10.2.17
  firebase_remote_config: any

  # For local data
  hive: 2.2.1
  hive_flutter: 1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true


  assets:
    - asset/detail_icon/
    - asset/images/
    - asset/



  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro

